### PR TITLE
Allow risk levels to come from query string

### PR DESCRIPTION
**Pull request by arletterocks**
The query string parameters aren't obfuscated (e.g. they're still exposureRiskLevel and healthRiskLevel) but if they're incomplete or have goofy values, the page kicks back to the "unable to load data" messaging.

### CODE REVIEW

**Comment by lookfirst** [comment]
Wouldn't this totally destroy the back button?

**Comment by arletterocks** [comment]
@lookfirst It swaps out the generic URL for one with a query string after you've hit the results page, so the back button still works!

**Comment by imf** [comment]
This doesn't seem to meet the requirements:

Expected: https://survey-web-e9ipjhcz7.now.sh/results?health_risk=low&exposure_risk=high&is_symptomatic=false&fname=John&lname=Smith&phone=%28416%29%20112-1234&email=john.smith%40example.com&id=5003u00000Jfz8w would render a results page.

**Comment by arletterocks** [comment]
Updated after rereading the requirements.  😬  Now requires `id` and checks that `health_risk`, `exposure_risk`, and `is_symptomatic` are correctly formed. If any of those are bunk it defaults to the "Unable to load data" screen.

**Pull request merged**
